### ISSUE TITLE
Update default pipeline include to spacy_sklearn

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/rasa-api#2]
Is it possible to update earlier tags as well. At least the last few? If that is too hard then we should remove anything before the current that we are not using.

Test to make sure it's all working.

**Comment by dcalvom** [comment]
I think it's time-consuming but not hard. I will make the change

**Comment by wrathagom** [comment]
Thanks.

**Comment by bigman73** [comment]
How will the pipe line be controlled? Using an environment variable?

**Comment by dcalvom** [comment]
@wrathagom all the branches had been updated to use the `spacy_sklearn` pipeline

@bigman73 the pipeline configuration is done trough the [config file](https://github.com/samtecspg/rasa-api/blob/master/files/config.json file)

You need to change that file if you want to change rasa configuration.

**Comment by wrathagom** [comment]
@dcalvom @milutz the config file can be changed by mounting a file though right, with docker? Can we provide an example of that here and in the README.md?

**Comment by bigman73** [comment]
Awesome! I just pulled the latest re-build 0.8.10 image tag.

Results are so much better - confidence values makes sense.
Training was successful and fast on a small data set, I will keep testing on larger data sets

You guys really need to connect with Rasa.NLU core team. The work that you're doing is fantastic.
Just get the documentation to a much better level (I saw the other issue that was created).

From my perspective this ticket can be closed. I can train models, parse sentences and get status using your great docker containers.

**Comment by dcalvom** [comment]
Cool. Thanks for your comments @bigman73, we appreciate them!...I'm going to close your first issue.

**Comment by wrathagom** [comment]
@bigman73 just out of curiosity did you try the official rasa docker builds? We are actually really active with them on their repo and Gitter channel, but haven't touched their docker file. We've set this repo up in such a way that it works for our team in our development environment really well. We're happy with it, but don't want to impose what works well for us onto the RASA repo/dockerfile.
