### ISSUE TITLE
Write some better docs

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/rasa-api#3]
Include the straight `docker run` command as well as a compose example. We need to talk about how to change out the config files as mount paths. Bonus points if we can expose the default config files provided by the RASA repo

**Comment by dcalvom** [comment]
Current status

- [ ] Update documentation given changes on RASA 0.8.*
- [ ] Create a compose example
- [ ] Provide example of how to mount config file

**Comment by wrathagom** [comment]
@dcalvom did we forget about these? Specifically need the 3rd check above for @bigman73 request on #6

**Comment by wrathagom** [comment]
Let's not forget about this one.

**Comment by wrathagom** [comment]
Closing since we're going to do this all in the rasa repo
