### ISSUE TITLE
Feature request - Expose the pipeline configuration setting as an environment variable

### ISSUE THREAD

**Issue by bigman73** [samtecspg/rasa-api#6]
Rasa NLU allows setting a custom pipeline
https://rasa-nlu.readthedocs.io/en/latest/pipeline.html#pre-configured-pipelines

> Creating your own pipelines is possible by directly passing the names of the components to rasa NLU in the pipeline configuration variable, e.g. "pipeline": ["nlp_spacy", "ner_crf", "ner_synonyms"]

Specifically I'm interested in adding ner_duckling for dates and numbers
https://rasa-nlu.readthedocs.io/en/latest/pipeline.html#ner-duckling

The logs show that "duckling_dimensions": null
Alternatively, can you add ner-duckling to the default docker images?

**Comment by wrathagom** [comment]
as for ner_duckling we've actually had really bad luck with it :( so we don't use it. @milutz maybe we should just run the RASA guys dev-requirements.txt install? Or maybe we support three tags `_minimal`, `_full`, and `_custom`?

**Comment by bigman73** [comment]
So basically the config file is already exposed?
To get it to show I just need to "mount the volume" on the docker container creation?

**Comment by bigman73** [comment]
Regarding dates and numbers - I have no attachment to duckling. 
What do you guys use for that purpose? Is it done as part of Rasa or as a preprocessing step?

**Comment by wrathagom** [comment]
Sorry, I should have said we don't use the duckling inside of Rasa. Instead we use this duckling REST wrapper. essentially we pass text through Rasa to get intents/entities and then we pass it through duckling to get dates/etc then we return it.

https://hub.docker.com/r/samtecspg/duckling/

**Comment by milutz** [comment]
@bigman73 how do you use the image? Are you using a docker-compose.yml to bring it up?

The blob that @wrathagom offered above (specifically the ```"${RASA_CONF:-./rasa-config.json}:/usr/src/rasa_nlu/config.json"``` part) would expose the config file.  But thats the syntax for a ```docker-compose.yml```, text close to that would also work for a ```-v``` on the ```docker``` command line.

**Comment by bigman73** [comment]
I just pulled the docker image from dockerhub, I  do not use docker-compose.yml
Yes, I was asking if the -v argument would get the config volume to show .

**Comment by milutz** [comment]
I just added one to the post above.  Are you on unix/Mac or windows?  (If on unix and it complains about the above -v, then try ```-v `pwd`/rasa-config.json:/usr/src/rasa_nlu/config.json```)

**Comment by milutz** [comment]
@bigman73 ... when you say "config volume" do you want more then the ```config.json``` ?  The example I gave is _just_ to expose the ```config.json```

**Comment by bigman73** [comment]
Sorry, I should have been clearer. I think that for custom pipelines I just need access to config.json.

**Comment by milutz** [comment]
@bigman73 so did 

> ``` -v ./rasa-config.json:/usr/src/rasa_nlu/config.json```
(If windows change the ```./rasa-config.json``` to an absolute path to the file you want to use)

or

> ```-v `pwd`/rasa-config.json:/usr/src/rasa_nlu/config.json```

Work for you ?

**Comment by bigman73** [comment]
I'll try that and report. Thanks for your help!

As for the duckling docker with rest, totally awesome. Will test that too.

**Comment by bigman73** [comment]
The duckling docker image works great.
But I did get some warnings:
`no port specified, defaulting to port 8000
Listening on http://0.0.0.0:8000
Can't open log file "log/error.log".
Exception: log/error.log: openFile: does not exist (No such file or directory)
Logging to stderr instead. **THIS IS BAD, YOU OUGHT TO FIX THIS**
2017-06-26T19:52:20.851772110Z 
Can't open log file "log/access.log".
Exception: log/access.log: openFile: does not exist (No such file or directory)
Logging to stderr instead. **THIS IS BAD, YOU OUGHT TO FIX THIS**
2017-06-26T19:52:20.851780546Z `

What is the issue with the log files?

**Comment by milutz** [comment]
@bigman73 That warning is coming from the base duckling service, its noting something that would be bad if it wasn't for the fact that its running in docker, as docker will record logs for you - so with docker, the "BAD" behavior (losing to stderr/stdout) is the _desirable_ behavior.

As we (currently) are modifying duckling, there isn't any easy way to make the error not appear.

**Comment by bigman73** [comment]
Thanks for the detailed explanation.

Since we are at it and slightly off topic - is there any chance of exposing a spacy web interface, or a spacy docker, so that spacy entity extraction can be performed regardless of Rasa NLU? (similarly to how Duckling docker is built)

**Comment by milutz** [comment]
@bigman73 I haven't dug in deep, but my understanding was that spacy was included at a library level, and hence didn't have any interface to expose.  If thats not the case let me know.

**Comment by wrathagom** [comment]
What would the end goal be trying to remove Rasa? You could write your own code do expose SpaCy via API, but you'd end up writing a lot of what the Rasa guys have done.

**Comment by bigman73** [comment]
@milutz 
I found a docker rest for spacy but it doesn't work. I opened an issue but no answer.
https://github.com/jgontrum/spacy-api-docker
You guys are very active and responsive and produce high quality docker images. 
I figured this is the best place for NLP docker images. Rasa and Duckling are already working, why not add more capabilities?

@wrathagom  I don't want to remove Rasa. It works great as an intent classifer. But I am performing entity extraction as a **pre processing** step.
Duckling will also be used this way.

Thanks again.

**Comment by wrathagom** [comment]
Why are you doing entity extraction that way if you don't mind me asking?

**Comment by bigman73** [comment]
It is part of a much bigger algorithm and system. The intent classification doesn't have to be combined with the entity extraction. Extracted entities can be manipulated to enhanced intent classification, and manual entity extraction gives more control.

**Comment by wrathagom** [comment]
Now you've peaked my interested because we too are working some a bit larger than just Rasa and are also implementing a way for entities to enhance or at least improve intent confidence.

**Comment by wrathagom** [comment]
Can we consider this one closed?

**Comment by bigman73** [comment]
@wrathagom Yes, I think we can close this item. I'll still try to mount the "volume" for the config file.
